[package]
name = "mcp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rustapi-rs = { workspace = true, features = ["toon"] }
serde = { workspace = true }
tokio = { workspace = true }
utoipa = { workspace = true }
