[package]
name = "microservices"
version = "0.1.0"
edition = "2021"

[dependencies]
rustapi-rs = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
utoipa = { workspace = true }
